Introduce notifications
This commit adds a new provider component that will allow the display of
snackbar notifications.

Notifications can be queued up using the `useNotifications` hook
provided by the context:

```javascript
const { queueNotification } = useNotifications()

queueNotification("success", "Wallet connected!")
```

We can also provide additional information via the subtitle property.
This can be used to pipe in an error message from an exepection, for
example:

```javascript
  const { connect, connectors, isConnected } = useConnect({
    onError: (error) =>
      queueNotification('error', 'Error conncecting wallet', error.message),
  })
```

A follow up PR will introduce this new notification ability to our
web3-related functionality